### ISSUE TITLE
Server side rendering 

### ISSUE THREAD

**Issue by arian-h** [sakren/node-google-maps#11]
We use this library for our client side rendering and it works fine. The problem is when we want to have server side rendering. 

For server side rendering, we use our own simple javascript call to google maps api and in return we get a picture. But as we `require` this library in our code , an error is returned because `window` object is not available. 

Can this be considered as an issue ? How can we stop the code running only because of being required ?

**Comment by sakren** [comment]
Hello, unfortunately this library could not be runned in node environment (yet?) since it's just simple loader for google's library.

Like I said [here](https://github.com/sakren/node-google-maps/issues/1#issuecomment-31453798) it would require writing complete library (with direct API calls to google maps) on my own, not just loader for some other library. Which is obviously much more simple.

I'm really sorry, that I could not be more helpful but this "problem" is just way too complex  and would go against the main advantage of this library - simplicity
